### ISSUE TITLE
Limited use in private windows

### ISSUE THREAD

**Issue by Lej77** [piroor/tst-more-tree-commands#19]
Since this extension doesn't register with Tree Style Tab it is not possible enable it inside the `Permissions for API Call from Other Addons` section of TST's option page. This prevents many commands such as `Flatten tree` from working in private windows.

**Comment by piroor** [comment]
TST Lock Tree Collapsed depends on notification messages from TST so it definitely registers itself to TST. Here is a screenshot on my environment, TST Lock Tree Collapsed appears at the last line in the image:
![image](https://user-images.githubusercontent.com/70062/163783248-396b001f-ff38-40e4-b007-ea47161fafaa.png)

 Could you try reloading TST Lock Tree Collapsed?

**Comment by piroor** [comment]
Oops sorry I misunderstood where this issue is owned...

**Comment by piroor** [comment]
Done with the commit 16b47a7.
![image](https://user-images.githubusercontent.com/70062/163784000-450af6e8-9fd9-4dce-a0c4-b2856c08017d.png)

**Comment by Lej77** [comment]
Thank you for taking the time to fix this issue, I appreciate it!
