### ISSUE TITLE
"Create New Group from Tabs" Breaks Some Functionality By Recent Update Version 1.4 Compared To Version 1.3

### ISSUE THREAD

**Issue by joshuagames987** [piroor/tst-more-tree-commands#21]
Recently I've noticed odd behaviors around how TST More Tree Commands works, after realizing that I troubleshooted reasons that it may be happening & came to the conclusion its definitely this extension, this is what I tried to come to this conclusion:
I tried using the newest version of TST with v1.3 of this extension aka the 2nd newest version by manually installing both using about:debugging, in a new profile negating any reasons that I may be to blame including changing any advanced Firefox settings or any settings/updates related to how TST itself works
I've realized 2 ways it no longer works:
1. You can no longer create groups within groups with using bookmark url: "ext+treestyletab:group?title=" as the context menu way of doing so no longer works & is greyed out, before this update as long as you had at least one more tab outside or one less tab inside current group selected it was possible to create a new group around  or inside another already existing group this behavior no longer exist
2. Creating a group with tabs including any children causes them to all be flattened to children of group tab instead of keeping original tree structure from before grouping action. Example: Imagine A1 & B1 are root tabs & A2 is a child of A1, selecting all 3 & creating a group flattens any children removing A1's child tab & makes it a child of group tab making the order of children of group tab A1,A2 & B2 instead of keeping any indentation.

**Comment by emvaized** [comment]
Sorry for long response. 
I am the author of changes for "Create group" functionality, which came with 1.4 update. Sorry to hear it caused problems for you.

As for 1st problem, I can totally see why it happens – with new condition for enabling the context menu entry I haven't thought of use cases when you have group inside another group. Could you please download [my fork](https://github.com/emvaized/tst-more-tree-commands) and test, if this problem still occurs there?

As for the second problem, I'm not really sure why it may happen – the logic when user has more than one tab selected remained untouched in 1.4. Are you sure this behavior was different in previous version?

**Comment by joshuagames987** [comment]
Yes I extracted the files from your fork and combined them with the extracted most recent copy of tst-more-commands by piroor & together they did work to fix both issues, also the second issue makes more sense if I just was to say it caused any indented tabs of higher parts of tree where groups were created                                                                                             all tabs selected before using the group context menu item to be flattened to the outmost part of the group keeping the order of all tabs but not the indent that made it possible to discern which tabs were connected to other tabs. Take these 5 tabs right here in image 1 the first 4 are connected one indent in each time with the last being on the same level as the 2nd
![Screenshot_2022 09 01_8](https://user-images.githubusercontent.com/97772714/187956533-21fa673d-7b31-4e48-9c79-be3f1b68e288.png)

when using the group command with no other modifications besides the group command on all 5 tabs results in image 2
![Screenshot_2022 09 01_9](https://user-images.githubusercontent.com/97772714/187956552-0ce7adae-391d-4749-8bfc-57134ee179f7.png)

This behavior is unlike v1.3 I have a copy if you'd like me to upload it.

**Comment by emvaized** [comment]
I just tested it with recent changes in my fork, and it seems both issues are resolved. When I create a new group, the indentation is kept. I will submit pull request now.

**Comment by piroor** [comment]
I close this with the merged PR. Thanks!
