### ISSUE TITLE
When creating a new group the generated folder title is "gibberish" (not plain text)

### ISSUE THREAD

**Issue by fragande** [piroor/tst-more-tree-commands#23]
As topic states. When using `Create New Group from tabs` the auto-generated folder title seems to be in a string format (?) instead of plain text, like this:

![bild](https://user-images.githubusercontent.com/24630657/194706885-e46bb405-483f-41ab-98ed-b8b6026bebb1.png)

By clicking in the name field on the tab page it's correctly "translated" into plain text:

![bild](https://user-images.githubusercontent.com/24630657/194707595-706f1d0d-d281-4b01-b25b-966b0c329994.png)
![bild](https://user-images.githubusercontent.com/24630657/194707515-fbe910e6-d912-49a4-87c4-89cc4dd7f658.png)

When creating several new groups at the same time this becomes a bit confusing if you don't manually rename the folders immediately.

**Comment by piroor** [comment]
This is a bug of TST itself. The commit https://github.com/piroor/treestyletab/commit/8548f03ef4bab2433bc1543c6622e96137c7157f on TST should fix it.
