### ISSUE TITLE
Add a way to rename tabs

### ISSUE THREAD

**Issue by brettz9** [piroor/tst-more-tree-commands#24]
Thanks for the excellent add-ons!

Sometimes the given name of a tab is useless or confusing. The ability to right-click and rename a tab (especially the parent tab) would be very useful for organizing tasks.

**Comment by piroor** [comment]
There is an addon for the purpose: Rename Tab Title
https://addons.mozilla.org/en-US/firefox/addon/rename-tab-title/
It does not provide context menu command and you need to use its toolbar button. I recommend you to request supporting tab context menu - it will work together with TST well.

**Comment by brettz9** [comment]
Thanks, I found this which does have a context menu: https://addons.mozilla.org/en-US/firefox/addon/tab-mix-rename-tab/

Only wish it would allow renaming new tabs so one could arbitrarily name empty parent tabs.
