### ISSUE TITLE
[Feature request] Allow for more than 1 More Tree Commands other when opting for not using "All"

### ISSUE THREAD

**Issue by SHHSSH** [piroor/tst-more-tree-commands#29]
Hi, @piroor 
Currently the options only allow for usage of 1 custom additional command to be selected, this is problematic for those who would like to keep a relatively minimal context menu but would still like to use more less all the commands but more than one.

Would you please implement the capability for the user to be able to select more than just 1 additional command instead of having to select "all"? I only require two at the moment, indent & flatten tree but feasibly see myself using outdent and maybe others in the future.

This particularly helps with allowing the user to indent/outdent a tab without having it load.
This can help with cases where say for example you've got a page with immense amounts of data on it(an AI interface chat perhaps like with Perplexity) and would like to organise its position without having to load the page.

![capture_006_27062024_062204](https://github.com/piroor/tst-more-tree-commands/assets/21285581/64993461-4c76-46eb-8639-9c07ca95178e)

Thanks as always.

**Comment by piroor** [comment]
It is impossible due to a restriction of WebExtensions API based addon. Firefox does not allow to provide multiple top level menu items, and Firefox automatically groups them under single submenu.
