### ISSUE TITLE
[Issue] Outdenting of tab from within a tree causes tab to become invisible

### ISSUE THREAD

**Issue by SHHSSH** [piroor/tst-more-tree-commands#30]
Outdenting a tab from within a tree unfortunately causes the tab to become invisible(the outdenting does function correctly however).

I have tested settings to see if it was "Show hidden tabs from other extensions" etc.

However it still does not work.
I have begun utilising both the indenting/outdenting hotkeys within this addon's hotkeys due to some malfunction lately with dragging into trees but I did not create an issue for this in TST because it may just be because of my Firefox personally.

Thank you for your consideration and endless efforts @piroor

**Comment by SHHSSH** [comment]
I'm not personally phased by this anymore as the helper addon TST Number Navigation is able to work correctly with its outdent-tree-safe and indent :)

So unless you care to change this for others @piroor no worries mate.

**Comment by piroor** [comment]
Sorry I couldn't reproduce this with regular conditions. There may be some missing steps to reproduce. Could you add screenshots of the tree before/after the problem happen? Screenshots will help me to understand the situation when the problem happens.
